version: '3'
services:
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    ports:
      - "3000:3000"
    networks:
      - cybernet

  kali:
    image: kalilinux/kali-rolling
    container_name: kali
    privileged: true
    networks:
      - cybernet
    tty: true
networks:
  cybernet:
    driver: bridge
